# config.yaml

app:
  host: 127.0.0.1
  port: 8080
  mode: debug # 可以是 debug 或 release

# Mysql 结构体是空的，可以暂时不写或留空
mysql: {}

redis:
  host: 127.0.0.1
  port: 6379
  password: "" # 如果你的 Redis 有密码，请填写
  db: 0

ai:
  # 对应 volcengineApi 结构体
  cut-out:
    url: ""
    region: ""
    service: ""
    method: ""
    content-type: ""
    action: ""
    version: ""
    access-id: ""
    secret-key: ""

  # 对应 tencentCloudApi 结构体
  face-fusion:
    url: "facefusion.tencentcloudapi.com"
    secret-id: "对线绝对压制" # 腾讯云 Secret ID
    secret-key: "自信诠释手法" # 腾讯云 Secret Key
    project-id: "冷静突破束缚"          # 活动ID
    action: "黄昏冰冷心绪"
    version: "沉沦回忆幻境"
    region: "06天才双边"
    rsp-img-type: "终将打破枷锁" # 这行没用，还是让前端自行选择返回格式吧。返回图片的格式，可以是 url 或 base64