app:
  name: "CloudPhoto"
  host: "localhost"
  port: 23322
  mode: "debug"

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  database: "cloudphoto"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

ai:
  cut-out:
    url: "https://visual.volcengineapi.com"
    region: "cn-north-1"
    service: "cv"
    method: "POST"
    content-type: "application/json"
    action: "CVProcess"
    version: "2022-08-31"
    access-id: "z"
    secret-key: "z"
